server:
  port: 8765

spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/yn-prison?useUnicode=true&characterEncoding=utf8&allowMultiQueries=true&&useSSL=false&autoReconnect=true
    username: root
    password: root
  cloud:
    config:
      discovery:
        enabled: true
        service-id: yunnan-config-server
      profile: zz
pagehelper:
  helperDialect: mysql
  reasonable: true
  supportMethodsArguments: true
  params: count=countSql

mybatis:
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package:  com.isoftstone.prison.yunnanbusinessserver.mapper
  configuration:
    map-underscore-to-camel-case: true

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/


